-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Mar 10 Mai 2016 à 19:01
-- Version du serveur :  10.1.10-MariaDB
-- Version de PHP :  5.6.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `soul_5mai`
--

--
-- Contenu de la table `membre`
--

UPDATE `membre` SET `mem_id` = 1,`mem_login` = 'domduf',`mem_mdp` = 'Dom-2016',`mem_persona` = 'Gestionaire',`mem_activite` = 'oui',`mem_description_musico` = 'le plus long',`mem_civilite` = 'M.',`mem_nom` = 'Dufour',`mem_prenom` = 'Dominique',`mem_date_naiss` = '1967-03-26',`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Dominique est un tromboniste formé au conservatoire d''Orléans par Monsieur Alain Recordier.\r\nUn peu paresseux, son surnom est "l''escargot"...',`mem_lien_photo` = './images/musicos/Dom.jpg',`mem_membre_bureau` = NULL,`mem_email` = 'dom.duf@coucou.com',`mem_adres_num` = 5,`mem_adres_rue` = 'rue de la Motte',`mem_adres_cp` = '45170',`mem_adres_ville` = 'NEUVILLE AUX BOIS' WHERE `membre`.`mem_id` = 1;
UPDATE `membre` SET `mem_id` = 2,`mem_login` = 'bobol',`mem_mdp` = NULL,`mem_persona` = 'Mobinaute',`mem_activite` = 'oui',`mem_description_musico` = 'le plus responsable',`mem_civilite` = 'M.',`mem_nom` = 'Bolard',`mem_prenom` = 'Christian',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Christian, dit Bobol est le fondateur et président du groupe.\r\nIl a joué dans un groupe de bal très connu avec Jeff son mentor.\r\nMalgrès son grand âge (il est en 1953) c''est le plus jeune de tous. ',`mem_lien_photo` = './images/musicos/Bol.jpg',`mem_membre_bureau` = 'président',`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 2;
UPDATE `membre` SET `mem_id` = 3,`mem_login` = 'dine',`mem_mdp` = NULL,`mem_persona` = 'Internaute',`mem_activite` = 'oui',`mem_description_musico` = 'la plus belle',`mem_civilite` = 'Mme',`mem_nom` = NULL,`mem_prenom` = 'Sadrine',`mem_date_naiss` = NULL,`mem_sexe` = 'feminin',`mem_centre_interet` = NULL,`mem_article` = 'Sandrine chante depuis peu...mais quel talent !\r\nElle fait vibrer d''émotion tout auditeur, même le plus insensible.\r\nLe Brass Band Val de Loire a fait appel a elle pour chanter un générique d''un des James Bond, le Big Band de Saran a la joie  de la mettre en avant lors de ses concerts.',`mem_lien_photo` = './images/musicos/Dine.jpg',`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 3;
UPDATE `membre` SET `mem_id` = 4,`mem_login` = 'stfgim',`mem_mdp` = NULL,`mem_persona` = 'Internaute',`mem_activite` = 'oui',`mem_description_musico` = 'le plus souple',`mem_civilite` = 'M.',`mem_nom` = 'Gimonet',`mem_prenom` = 'Stephane',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Stéphane, dit "Mister Lips" est le pointeur (celui qui joue dans l''aigü) de la section de cuivre.\r\nD''une formation informatique, il a préféré  garder la musique comme activité secondaire, mais ses capacités sont terribles !',`mem_lien_photo` = './images/musicos/StfG.jpg',`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 4;
UPDATE `membre` SET `mem_id` = 5,`mem_login` = 'philippe',`mem_mdp` = 'Phil-2016',`mem_persona` = 'Gestionaire',`mem_activite` = 'non',`mem_description_musico` = NULL,`mem_civilite` = 'M.',`mem_nom` = 'Bouquet',`mem_prenom` = 'Philippe',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = NULL,`mem_lien_photo` = NULL,`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 5;
UPDATE `membre` SET `mem_id` = 6,`mem_login` = 'hery',`mem_mdp` = 'Hery-2016',`mem_persona` = 'Gestionaire',`mem_activite` = 'non',`mem_description_musico` = NULL,`mem_civilite` = 'M.',`mem_nom` = 'Ratsimbasafy',`mem_prenom` = 'Hery',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = NULL,`mem_lien_photo` = NULL,`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 6;
UPDATE `membre` SET `mem_id` = 7,`mem_login` = 'michelD',`mem_mdp` = NULL,`mem_persona` = NULL,`mem_activite` = 'oui',`mem_description_musico` = 'le plus grand',`mem_civilite` = 'M.',`mem_nom` = 'Delalande',`mem_prenom` = 'Michel',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Michel est un organiste hors pair, mais ses qualités sont surtout dans le timbre de sa voix.\r\nNe le surnomme-t-on pas "Michel Cooker"..?',`mem_lien_photo` = './images/musicos/Michel.jpg',`mem_membre_bureau` = 'trésorier',`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 7;
UPDATE `membre` SET `mem_id` = 8,`mem_login` = 'ribus',`mem_mdp` = NULL,`mem_persona` = NULL,`mem_activite` = 'oui',`mem_description_musico` = 'le plus rapide',`mem_civilite` = 'M.',`mem_nom` = 'Ribet',`mem_prenom` = 'Fabien',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Ribus joue plus vite que son ombre, mais ce n''est pas le plus important.\r\nIl connait tout le répertoire par coeur, c''est la bible rythmique, et même parfois mélodique du groupe.\r\nUn homme à suivre.',`mem_lien_photo` = './images/musicos/Ribus.jpg',`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 8;
UPDATE `membre` SET `mem_id` = 9,`mem_login` = 'stfD',`mem_mdp` = NULL,`mem_persona` = NULL,`mem_activite` = 'oui',`mem_description_musico` = 'le plus fort',`mem_civilite` = 'M.',`mem_nom` = 'Delalande',`mem_prenom` = 'Stéphane',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Stéphane joue à peu près de tout, mais surtout de la basse.\r\nOn l''a vu longtemps au Brass Band Val de Loire, au premier trombone.\r\nIl joue également du trombone dans le groupe "O Jazz O".\r\nAvec Ribus, il assure le groove qui a fait la renommée de Soul Latitude.',`mem_lien_photo` = './images/musicos/StfD.jpg',`mem_membre_bureau` = 'secrétaire',`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 9;
UPDATE `membre` SET `mem_id` = 10,`mem_login` = 'arnoG',`mem_mdp` = NULL,`mem_persona` = NULL,`mem_activite` = 'oui',`mem_description_musico` = 'le plus agile',`mem_civilite` = 'M.',`mem_nom` = NULL,`mem_prenom` = 'Arno',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Grand et élancé, Arno est capable de jouer la plus calme des mélodie, comme le plus terrible des riff.\r\nD''une culture musicale impressionante, il retrouvera le phrasé des plus grands.',`mem_lien_photo` = './images/musicos/ArnoGuitare.jpg',`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 10;
UPDATE `membre` SET `mem_id` = 11,`mem_login` = 'nono',`mem_mdp` = NULL,`mem_persona` = NULL,`mem_activite` = 'oui',`mem_description_musico` = 'le plus charmeur',`mem_civilite` = 'M.',`mem_nom` = 'Bolard',`mem_prenom` = 'Arnaud',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Arnaud, dit Nono peut vous transporter.\r\nAvec quoi ? Son saxophone alto, qu''il manie tel Lou Marini.\r\nLaissez vous faire.',`mem_lien_photo` = './images/musicos/Nono.jpg',`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 11;
UPDATE `membre` SET `mem_id` = 12,`mem_login` = 'pip',`mem_mdp` = NULL,`mem_persona` = NULL,`mem_activite` = 'oui',`mem_description_musico` = 'le plus câlin',`mem_civilite` = 'M.',`mem_nom` = 'Julien',`mem_prenom` = 'Philippe',`mem_date_naiss` = NULL,`mem_sexe` = 'masculin',`mem_centre_interet` = NULL,`mem_article` = 'Ne vous méprenez pas, sous des dehors de calme et de sérenité, un homme d''un rare tempérament se cache.\r\nPeu de difficulté sauront lui resister, et ses chorus en ont éblouies plus d''une...',`mem_lien_photo` = './images/musicos/Pip.jpg',`mem_membre_bureau` = NULL,`mem_email` = NULL,`mem_adres_num` = NULL,`mem_adres_rue` = NULL,`mem_adres_cp` = NULL,`mem_adres_ville` = NULL WHERE `membre`.`mem_id` = 12;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
